[package]
name = "logi-forge-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
logi-forge-core = { path = "../logi-forge-core" }
logi-forge-hidpp = { path = "../logi-forge-hidpp" }
evdev = "0.13"

[lints]
workspace = true
